name: voiceanize

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  provider: ^4.3.1
  flutter_spinkit: ^4.1.2+1
  mime: ^0.9.6+3
  validators: ^2.0.0
  alan_voice: ^2.0.7
  flutter_rating_bar: ^3.0.1+1
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  gradient_text: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true